name: Angular CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4   # ✅ updated

    - name: Setup Node
      uses: actions/setup-node@v4   # ✅ updated
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build
